### ISSUE TITLE
Prevent hacking from indians

### ISSUE THREAD

**Issue by zabealbe** [eagletrt/eagletrt-telemetria-ip#4]
Having the ssh username in a service exposed on the internet  (https://eagletrt-telemetria-ip.herokuapp.com/) is a big nono

**Comment by euberdeveloper** [comment]
Però è utile

**Comment by zabealbe** [comment]
How much do indians pay you

**Comment by euberdeveloper** [comment]
A lot. The problem is that their Rupie are worth nothing. 

No il punto è che andrà messo anche su altra roba tipo il volante eccetera, quindi per farlo che va dappertutto serve

**Comment by bonnee** [comment]
Not necessary actually, username should be provided by the user like in proper ssh.
A neat thing could be to integrate shi.sh into ssh config to automatically have username and private keys configured
