### ISSUE TITLE
prevent nerds from stating that your software is bloated

### ISSUE THREAD

**Issue by zabealbe** [eagletrt/eagletrt-telemetria-ip#5]
Using a node app as a client is unnecessary. If the server accepts simple http requests a system based on wget with minimal requirements should be preferred.

**Comment by bonnee** [comment]
Yea nodejs should not be installed on a poor innocent raspberry pi. I will rewrite the client in sh

**Comment by euberdeveloper** [comment]
By using curl, you end up with this stuff `curl -sH "Content-Type: application/json" -d "{ \"ngrokUrl\":\"$ngrok_url\", \"localIp\":\"$local_ip\", \"publicIp':\"$public_ip\", \"user\":\"$user\" }"` and tanti auguri if you want to find the bug

**Comment by euberdeveloper** [comment]
Resolved by keeping both the options
